#!/bin/bash
freq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)
gov=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
temp=$(cat /sys/devices/virtual/thermal/thermal_zone0/temp)

echo "CPU temp           :   $(( temp / 1000 ))°C"
echo "CPU freq           :   $(bc <<< "scale=0; $freq/1000") MHz ($gov)"
echo "CPU usage          :   $(top -d 0.5 -b -n2 | grep "Cpu(s)"|tail -n 1 | awk '{print $2 + $4}')%"