#!/bin/bash

cd ~/xmrig
echo "cleaning..."
git clean -f -d -x
rm -fr build

echo "updating"
git pull

echo "building"
mkdir build
cd build

export CC=clang
export CXX=clang++

flags="-Ofast -march=native -mtune=native"

flags="$flags -flto=thin"

flags="$flags -ffast-math -fsigned-zeros -fhonor-infinites"

flags="$flags -mllvm -polly"

flags="$flags -mllvm -polly-vectorizer=stripmine"

flags="$flags -mllvm -polly-parallel -mllvm -polly-scheduling=dynamic"
flags="$flags -mllvm -polly-omp-backend=LLVM"

flags="$flags -mllvm -polly-scheduling-chunksize=16"

ldflags="-O2 -fuse-ld=lld -flto=thin"

cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_NVML=OFF -DCMAKE_C_FLAGS="$flags" -DCMAKE_CXX_FLAGS="$flags" -DCMAKE_EXE_LINKER_FLAGS="$ldflags"
make -j4

echo "copying binary"
cp -v xmrig ~/bin/xmrig
